baseURL = 'https://aadishv.github.io'
languageCode = 'en-us'
title = 'Aadish Verma'
theme = 'archie'
copyright = "© Aadish Verma"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
subtitle = """
**Chemistry quick links:**
[aufbau](/chemutils/aufbau.jpg)・
[bonding shapes](/chemutils/bonding.avif)・
[solubility](/chemutils/solubility.webp)

Student at Stanford Online High School, passionate about really anything [but especially STEM]. A few notable things I've done:

Won the OHS 2024 Labor Day Hackathon. I might write a blog post about it later :) [[code](https://github.com/aadishv/doleofdoves)]

[Advent of Code](https://adventofcode.com/2024) 2024 participant. [[code](https://github.com/aadishv/aoc)]

Lead coder for VEX V5 Robotics Competition team [315P](https://www.robotevents.com/teams/V5RC/315P) for Over Under and part of the High Stakes seasons. [My code is unfortunately private, I will try to make a public mirror available soon.]

No blog posts yet, but a few in the works :)
"""
mode = "auto" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
katex = true # enable KaTeX support
customcss = ["css/code.css"] # custom css files
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/aadishv"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
